version: "1"
rules:
  - base: Petercord-Userbot
    upstream: Petercord-Plugins:Petercord-Userbot
    mergeMethod: rebase
    mergeUnstable: false
  - base: Petercord-Userbot
    upstream: Petercord-Plugins:Petercord-Userbot
    mergeMethod: rebase
  - base: Petercord-Userbot
    upstream: Petercord-Plugins:Petercord-Userbot
    mergeMethod: rebase
